name: Renee Jacobs
favicon: null
layout_spectrum: 0.9988321627024561
typography_spectrum: 0.5125906304456294
title: Design Portfolio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.029373787809163332
  lightness: 0.25151982600800693
  saturation: 0.12383623910136521
  rhythmicContrast: 0.2377448610495776
purpose: []
